version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: travel_planner_db
    environment:
      POSTGRES_DB: travel_planner
      POSTGRES_USER: travel_user
      POSTGRES_PASSWORD: travel_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: travel_planner_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@travelplanner.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: 