"""Add booking and travel plan tables

Revision ID: 64af1270e238
Revises: fa58a4c6485c
Create Date: 2025-06-29 18:01:44.042575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64af1270e238'
down_revision = 'fa58a4c6485c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 